name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Install Antlr & other apt packages.
      run: sudo apt-get -y install antlr4=4.7.2-5
    - name: Generate Antlr files.
      run: antlr4 -Dlanguage=CSharp -no-listener -visitor ./Grammar/iro.g4
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
